# Generated by Django 3.2.7 on 2021-09-21 12:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_alter_profile_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_logo',
            field=cloudinary.models.CloudinaryField(default='/static/images/linkerd.svg', max_length=255, verbose_name='image'),
        ),
    ]
