# Generated by Django 3.2.7 on 2021-09-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0004_business_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_details',
            field=models.TextField(null=True),
        ),
    ]
